### ISSUE TITLE
compilation fails (ubuntu 14.04 / gcc 4.8.4)

### ISSUE THREAD

**Issue by sphericale** [traysi/x16rv2_hash#1]
I'm attempting to update Electrumx for the Ravencoin x16rv2 fork but having some trouble with the Python module

Although it compiles/installs fine on my Debian system, it is failing to build in the Travis CI test environment used by Electrumx

https://travis-ci.org/kyuupichan/electrumx/jobs/587495803

```
    x16rv2.c:125:13: error: ‘for’ loop initial declarations are only allowed in C99 mode
                 for (int j = 24; j < 64; ++j) ((uint8_t*)hash)[j] = 0; // Pad the 24 bytes to bring it to 64 bytes
                 ^
    x16rv2.c:125:13: note: use option -std=c99 or -std=gnu99 to compile your code
```

It seems that older versions of gcc require the -std=c99 flag to enable C99 support
but might be better (more compatible) just to move those variable declarations outside the loop

**Comment by traysi** [comment]
Thank you, I updated the code with this change.
